- hosts: all
  become: true
  tasks:
    - name: Update Repository Index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Packages on Ubuntu
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - htop
        state: latest

    - name: Update Repository Index
      dnf:
        update_cache: yes
      when: ansible_distribution == "Oracle Linux"

    - name: Install Packages on Oracle Linux
      when: ansible_distribution == "Oracle Linux"
      dnf:
        name:
          - httpd
          - php
          - htop
        state: latest
