---
- hosts: all
  become: true
  tasks:
    - name: Update Repository Index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

    - name: Install Apache
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

    - name: Add PHP support for Apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

    - name: Install htop
      apt:
        name: htop
        state: latest
      when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"
